Char_Space equ 0

Char_FighterBullet equ 128
Char_EnemyBullet equ 129
Char_Barrier equ 130
Char_BarrierHead equ 131
Char_Fighter equ 132
Char_SkyEnemy equ 136
Char_SkyEnemyA equ 136
Char_SkyEnemyB equ 140
Char_SkyEnemyC equ 172
Char_GroundEnemy equ 176
Char_Bang equ 184
Char_Item equ 204
Char_Fort equ 208
Char_Terrain equ 244
Char_Water equ 244
Char_Grass equ 245
Char_Concrete equ 246
Char_End equ 254

Char_Logo equ 48
Char_End2 equ 64
