Char_Space equ 0
Char_Ascii equ 0
Char_Wall equ 64

Char_Knife equ 72
Char_Knife_Left equ 72
Char_Knife_Right equ 73
Char_Knife_Up equ 74
Char_Knife_Down equ 75

Char_Man equ 80
Char_Man_Left equ 80
Char_Man_Left_Stop equ 80
Char_Man_Left0 equ 84
Char_Man_Left1 equ 88
Char_Man_Left2 equ 92
Char_Man_Left3 equ 96
Char_Man_Right equ 100
Char_Man_Right_Stop equ 100
Char_Man_Right0 equ 104
Char_Man_Right1 equ 108
Char_Man_Right2 equ 112
Char_Man_Right3 equ 116
Char_Man_Up equ 120
Char_Man_Up_Stop equ 120
Char_Man_Up0 equ 124
Char_Man_Up1 equ 128
Char_Man_Up2 equ 132
Char_Man_Up3 equ 136
Char_Man_Down equ 140
Char_Man_Down_Stop equ 140
Char_Man_Down0 equ 144
Char_Man_Down1 equ 148
Char_Man_Down2 equ 152
Char_Man_Down3 equ 156
Char_Man_Die2 equ 160
Char_Man_Die3 equ 164
Char_Chaser equ 168

Char_Disturber equ 176

Char_Goal equ 184

Char_Bang equ 192

Char_Title equ 200
Char_M equ 200

Char_A equ 208

Char_Z equ 216

Char_Y equ 224

Char_End equ 232
