
Char_Space equ 0
Char_Ascii equ 0
Char_Logo equ 64
Char_Floor equ 80

Char_LiftBottom equ 88

Char_Roof equ 96
Char_Roof_Center equ 96
Char_Roof_Left equ 97
Char_Roof_Right equ 98

Char_Item equ 104
Char_Item_A equ 104

Char_Item_B equ 112

Char_Item_C equ 120

Char_Item_D equ 128

Char_Remain equ 136

Char_End equ 144

Pattern_Man equ 0
Pattern_Man_Left equ 0
Pattern_Man_Left0 equ 0
Pattern_Man_Left1 equ 4
Pattern_Man_Left2 equ 8
Pattern_Man_Left3 equ 12
Pattern_Man_Left_Stop equ 16
Pattern_Man_Right equ 20
Pattern_Man_Right0 equ 20
Pattern_Man_Right1 equ 24
Pattern_Man_Right2 equ 28
Pattern_Man_Right3 equ 32
Pattern_Man_Right_Stop equ 36
Pattern_Man_Loose equ 40
Pattern_Monster equ 52
Pattern_Monster_Left equ 52
Pattern_Monster_Left0 equ 52
Pattern_Monster_Left1 equ 56
Pattern_Monster_Right equ 60
Pattern_Monster_Right0 equ 60
Pattern_Monster_Right1 equ 64
Pattern_Lift equ 68
Pattern_Point equ 72
Pattern_End equ 88
