
Char_Space equ 0
Char_Ascii equ 0
Char_Logo equ 64
Char_MovablePanel equ 80
Char_Star equ 88

Char_Remain equ 96

Char_Arrow equ 104
Char_ArrowH equ 104
Char_ArrowV equ 108
Char_End equ 112

Pattern_Man equ 0
Pattern_Man_Left equ 0
Pattern_Man_Left0 equ 0
Pattern_Man_Left1 equ 1
Pattern_Man_Right equ 2
Pattern_Man_Right0 equ 2
Pattern_Man_Right1 equ 3
Pattern_Man_Up equ 4
Pattern_Man_Up0 equ 4
Pattern_Man_Up1 equ 5
Pattern_Man_Down equ 6
Pattern_Man_Down0 equ 6
Pattern_Man_Down1 equ 7
Pattern_Monster equ 8
Pattern_Monster_Left equ 8
Pattern_Monster_Left0 equ 8
Pattern_Monster_Left1 equ 9
Pattern_Monster_Right equ 10
Pattern_Monster_Right0 equ 10
Pattern_Monster_Right1 equ 11
Pattern_Monster_Up equ 12
Pattern_Monster_Up0 equ 12
Pattern_Monster_Up1 equ 13
Pattern_Monster_Down equ 14
Pattern_Monster_Down0 equ 14
Pattern_Monster_Down1 equ 15
Pattern_MonserRev equ 16
Pattern_MonserRev_left equ 16
Pattern_MonserRev_Right equ 17
Pattern_MonserRev_Up equ 18
Pattern_MonserRev_Down equ 19
Pattern_End equ 20
