
Char_Cent equ 0
Char_Wall equ 1
Char_Box equ 5
Char_Item equ 9
Char_Ball equ 13
Char_Oneup equ 17
Char_Remain equ 21
Char_End0 equ 25


Char_Man equ 128
Char_Sword equ 132
Char_Monster equ 136
Char_End1 equ 152

Char_Space equ 32

Ptn_Cent equ 0
Ptn_Wall equ 1
Ptn_Box equ 5
Ptn_Item equ 9
Ptn_Ball equ 13
Ptn_Oneup equ 17
Ptn_Man equ 21
Ptn_Man_Left equ 21
Ptn_Man_Left0 equ 21
Ptn_Man_Left1 equ 25
Ptn_Man_LeftAttack equ 29
Ptn_Man_Right equ 37
Ptn_Man_Right0 equ 37
Ptn_Man_Right1 equ 41
Ptn_Man_RightAttack equ 45
Ptn_Man_Up equ 53
Ptn_Man_Up0 equ 53
Ptn_Man_Up1 equ 57
Ptn_Man_UpAttack equ 61
Ptn_Man_Down equ 69
Ptn_Man_Down0 equ 69
Ptn_Man_Down1 equ 73
Ptn_Man_DownAttack equ 77
Ptn_Monster equ 85
Ptn_Monster_Left equ 85
Ptn_Monster_Left0 equ 85
Ptn_Monster_Left1 equ 89
Ptn_Monster_Right equ 93
Ptn_Monster_Right0 equ 93
Ptn_Monster_Right1 equ 97
Ptn_Monster_Up equ 101
Ptn_Monster_Up0 equ 101
Ptn_Monster_Up1 equ 105
Ptn_Monster_Down equ 109
Ptn_Monster_Down0 equ 109
Ptn_Monster_Down1 equ 113
Ptn_End equ 117
