
Char_Space equ 0
Char_Ascii equ 0
Char_Logo equ 64
Char_Soil equ 80
Char_Wall equ 82
Char_Wall_Space  equ 82
Char_Wall_Left  equ 83
Char_Wall_Right  equ 84
Char_Wall_Top  equ 85
Char_Wall_Bottom  equ 86
Char_Wall_LeftTop  equ 87
Char_Wall_RightTop  equ 88
Char_Wall_LeftBottom  equ 89
Char_Wall_RightBottom  equ 90
Char_Bedrock equ 91
Char_Remain equ 92
Char_End equ 96

Pattern_Man equ 0
Pattern_Ghost equ 16
Pattern_Chaser equ 32
Pattern_Rock equ 33
Pattern_Point equ 34
Pattern_Loose equ 38
Pattern_Box equ 40
Pattern_End equ 41
