
Char_Space equ 0
Char_Ascii equ 0
Char_Logo equ 64
Char_Wall equ 80
Char_Card equ 96
Char_Color equ 152
Char_Remain equ 152
Char_End equ 156

Pattern_Solver equ 0
Pattern_Solver_Left equ 0
Pattern_Solver_Right equ 2
Pattern_Solver_Up equ 4
Pattern_Solver_Down equ 6
Pattern_Monster equ 8
Pattern_Monster_Left equ 8
Pattern_Monster_Right equ 10
Pattern_Monster_Up equ 12
Pattern_Monster_Down equ 14
Pattern_Card equ 16
Pattern_End equ 17
