
Char_Space equ 0
Char_Ascii equ 0
Char_Logo equ 64
Char_Block equ 80

Char_Item equ 88

Char_Remain equ 96

Char_Line equ 104
Char_Line_Yellow equ 104
Char_Line_RightBottom equ 104
Char_Line_LeftBottom equ 105
Char_Line_RightTop equ 106
Char_Line_LeftTop equ 107
Char_Line_Left equ 108
Char_Line_Right equ 109
Char_Line_Top equ 110
Char_Line_Bottom equ 111
Char_Line_Red equ 112
Char_End equ 120

Pattern_Man equ 0
Pattern_Man_Left equ 0
Pattern_Man_Left0 equ 0
Pattern_Man_Left1 equ 4
Pattern_Man_Right equ 8
Pattern_Man_Right0 equ 8
Pattern_Man_Right1 equ 12
Pattern_Man_Up equ 16
Pattern_Man_Up0 equ 16
Pattern_Man_Up1 equ 20
Pattern_Man_Down equ 24
Pattern_Man_Down0 equ 24
Pattern_Man_Down1 equ 28
Pattern_Monster equ 32
Pattern_Monster_Left equ 32
Pattern_Monster_Left0 equ 32
Pattern_Monster_Left1 equ 36
Pattern_Monster_Right equ 40
Pattern_Monster_Right0 equ 40
Pattern_Monster_Right1 equ 44
Pattern_Monster_Up equ 48
Pattern_Monster_Up0 equ 48
Pattern_Monster_Up1 equ 52
Pattern_Monster_Down equ 56
Pattern_Monster_Down0 equ 56
Pattern_Monster_Down1 equ 60
Pattern_Point equ 64
Pattern_Increaser equ 80
Pattern_End equ 84
