Char_Space equ 0
Char_Ascii equ 0
Char_Logo equ 64
Char_Soil equ 80

Char_Bedrock equ 88

Char_Wall equ 96
Char_Wall_Space equ 96
Char_Wall_Left equ 97
Char_Wall_Right equ 98
Char_Wall_Top equ 99
Char_Wall_Bottom equ 100
Char_Wall_LeftTop equ 101
Char_Wall_RightTop equ 102
Char_Wall_LeftBottom equ 103
Char_Wall_RightBottom equ 104

Char_Box equ 112

Char_Rock equ 120

Char_Remain equ 128

Char_End equ 136

Pattern_Man equ 0
Pattern_Ghost equ 64
Pattern_Chaser equ 96
Pattern_Rock equ 100
Pattern_Point equ 104
Pattern_Loose equ 120
Pattern_End equ 128
