
Char_Space equ 0
Char_Ascii equ 0
Char_Logo equ 64
Char_Fence equ 80
Char_Color equ 81
Char_Remain equ 81
Char_Block equ 85
Char_BlockA equ 85
Char_BlockB equ 89
Char_BlockC equ 93
Char_Ufo equ 97
Char_UfoU equ 97
Char_UfoL equ 101
Char_End equ 105

Pattern_Cannon equ 0
Pattern_CannonOn equ 0
Pattern_CannonOff equ 1
Pattern_Bullet equ 2
Pattern_Block equ 3
Pattern_BlockA equ 3
Pattern_BlockB equ 4
Pattern_BlockC equ 5
Pattern_Bang equ 6
Pattern_SmallBang equ 6
Pattern_LargeBang equ 7
Pattern_End equ 11
