
Char_Space equ 0
Char_Ascii equ 0
Char_Logo equ 64
Char_Star equ 80
Char_Barrier equ 96
Char_Map equ 100
Char_Remain equ 102
Char_Fort equ 106
Char_End equ 250

Pattern_Fighter equ 0
Pattern_Enemy equ 8
Pattern_FighterBullet equ 16
Pattern_EnemyBullet equ 20
Pattern_BarrierHead equ 21
Pattern_Bang equ 22
Pattern_SmallBang equ 22
Pattern_LargeBang equ 23
Pattern_Item equ 27
Pattern_FighterOnMap equ 28
Pattern_End equ 29
