
Char_Space equ 0
Char_Ascii equ 0
Char_Logo equ 64
Char_Ground equ 80
Char_GroundFlat equ 80
Char_GroundUp equ 81
Char_GroundDown equ 82
Char_Color equ 83
Char_Remain equ 83
Char_Fort equ 87
Char_End equ 115

Pattern_MyFighter equ 0
Pattern_MyFighter_Right equ 0
Pattern_MyFighter_RightDown equ 1
Pattern_MyFighter_RightUp equ 2
Pattern_EnemyFighter_Right equ 3
Pattern_EnemyFighter_Left equ 4
Pattern_Track equ 5
Pattern_Rocket equ 6
Pattern_SmallBang equ 7
Pattern_LargeBang equ 8
Pattern_Item equ 12
Pattern_MyBullet equ 13
Pattern_EnemyBullet equ 17
Pattern_End equ 21
