
Char_Space equ 0
Char_Ascii equ 0
Char_Logo equ 64
Char_Floor equ 79
Char_Ladder equ 80

Char_Bomb equ 88

Char_Flag equ 96
Char_Flag_A equ 96

Char_Flag_B equ 104

Char_Flag_C equ 112

Char_Flag_D equ 120

Char_Remain equ 128

Char_End equ 136

Pattern_Man equ 0
Pattern_Man_Left equ 0
Pattern_Man_Left_Stop equ 0
Pattern_Man_Left0 equ 1
Pattern_Man_Left1 equ 2
Pattern_Man_Left2 equ 3
Pattern_Man_Right equ 4
Pattern_Man_Right_Stop equ 4
Pattern_Man_Right0 equ 5
Pattern_Man_Right1 equ 6
Pattern_Man_Right2 equ 7
Pattern_Man_UpDown equ 8
Pattern_Man_UpDown0 equ 8
Pattern_Man_UpDown1 equ 9
Pattern_Man_Loose equ 10
Pattern_Man_Loose0 equ 10
Pattern_Man_Loose1 equ 11
Pattern_Man_Loose2 equ 12
Pattern_Monster equ 13
Pattern_Monster_Left equ 13
Pattern_Monster_Left0 equ 13
Pattern_Monster_Left1 equ 14
Pattern_Monster_Right equ 15
Pattern_Monster_Right0 equ 15
Pattern_Monster_Right1 equ 16
Pattern_Monster_Up equ 17
Pattern_Monster_Up0 equ 17
Pattern_Monster_Up1 equ 18
Pattern_Monster_Down equ 19
Pattern_Monster_Down0 equ 19
Pattern_Monster_Down1 equ 20
Pattern_Point equ 21
Pattern_Bang equ 25
Pattern_End equ 26
