
Char_Space equ 0
Char_Ascii equ 0
Char_Logo equ 64
Char_Remain equ 80
Char_Terrain equ 84
Char_End equ 94

Pattern_Fighter equ 0
Pattern_SkyEnemy equ 1
Pattern_SkyEnemyA equ 1
Pattern_SkyEnemyB equ 2
Pattern_SkyEnemyC equ 10
Pattern_GroundEnemy equ 11
Pattern_GroundEnemyA equ 11
Pattern_GroundEnemyB equ 12
Pattern_FighterBullet equ 13
Pattern_EnemyBullet equ 14
Pattern_Barrier equ 15
Pattern_BarrierLeft equ 15
Pattern_BarrierCenter equ 16
Pattern_BarrierRight equ 17
Pattern_Bang equ 18
Pattern_SmallBang equ 18
Pattern_LargeBang equ 19
Pattern_Item equ 23
Pattern_Fort equ 24
Pattern_End equ 33
