
Char_Man equ 128
Char_Monster equ 132
Char_FireBullet equ 148
Char_Fire equ 152
Char_Food equ 156
Char_End equ 160

Char_Space equ 0


Pattern_Man equ 0
Pattern_Man_Left equ 0
Pattern_Man_Left0 equ 0
Pattern_Man_Left1 equ 4
Pattern_Man_Right equ 8
Pattern_Man_Right0 equ 8
Pattern_Man_Right1 equ 12
Pattern_Man_Up equ 16
Pattern_Man_Up0 equ 16
Pattern_Man_Up1 equ 20
Pattern_Man_Down equ 24
Pattern_Man_Down0 equ 24
Pattern_Man_Down1 equ 28
Pattern_Monster equ 32
Pattern_Monster_Left equ 32
Pattern_Monster_Left0 equ 32
Pattern_Monster_Left1 equ 36
Pattern_Monster_Right equ 40
Pattern_Monster_Right0 equ 40
Pattern_Monster_Right1 equ 44
Pattern_Monster_Up equ 48
Pattern_Monster_Up0 equ 48
Pattern_Monster_Up1 equ 52
Pattern_Monster_Down equ 56
Pattern_Monster_Down0 equ 56
Pattern_Monster_Down1 equ 60
Pattern_FireBullet equ 64
Pattern_Fire equ 68
Pattern_Food equ 72
Pattern_End equ 76
