
Char_Space equ 0
Char_Ascii equ 0
Char_Logo equ 64
Char_Barrier equ 80
Char_Color equ 82
Char_Remain equ 82
Char_Terrain equ 86
Char_Fort equ 114
Char_Fort0 equ 114
Char_Fort1 equ 150
Char_End equ 192

Pattern_Fighter equ 0
Pattern_SkyEnemyA equ 1
Pattern_SkyEnemyB equ 2
Pattern_SkyEnemyC equ 10
Pattern_GroundEnemyA equ 11
Pattern_GroundEnemyB equ 12
Pattern_FighterBullet equ 13
Pattern_EnemyBullet equ 14
Pattern_BarrierHead equ 15
Pattern_Bang equ 16
Pattern_SmallBang equ 16
Pattern_LargeBang equ 17
Pattern_Item equ 21
Pattern_End equ 22
