IE0_ equ 10h
IE1_ equ 11h
IR0_ equ 12h
IR1_ equ 13h
P0_ equ 14h
P1_ equ 15h
P2_ equ 16h
P3_ equ 17h

P0C equ 20h
P1C equ 21h
P2C equ 22h
P3C equ 23h

MMU0 equ 24h
MMU1 equ 25h
MMU2 equ 26h
MMU3 equ 27h
MMU4 equ 28h

LCC equ 30h
LCH equ 31h
LCV equ 32h
DMC equ 34h
DMX1 equ 35h
DMY1 equ 36h
DMDX equ 37h
DMDY equ 38h
DMX2 equ 39h
DMY2 equ 3ah
DMPL equ 3bh
DMBR equ 3ch
DMVP equ 3dh

SGC equ 40h
SG0L equ 42h
SG1L equ 44h
SG0TH equ 46h
SG0TL equ 47h
SG1TH equ 48h
SG1TL equ 49h
SG2L equ 4ah
SG2TH equ 4ch
SG2TL equ 4dh
SGDA equ 4eh

TM0C equ 50h
TM0D equ 51h
TM1C equ 52h
TM1D equ 53h
CLKT equ 54h
