
Char_Space equ 0
Char_Logo equ 0
Char_Color equ 16
Char_Soil equ 16
Char_Bedrock equ 18
Char_Wall equ 19
Char_Wall_Space  equ 19
Char_Wall_Left  equ 20
Char_Wall_Right  equ 21
Char_Wall_Top  equ 22
Char_Wall_Bottom  equ 23
Char_Wall_LeftTop  equ 24
Char_Wall_RightTop  equ 25
Char_Wall_LeftBottom  equ 26
Char_Wall_RightBottom  equ 27
Char_Remain equ 28
Char_End equ 32

Pattern_Man equ 0
Pattern_Ghost equ 16
Pattern_Chaser equ 32
Pattern_Rock equ 33
Pattern_Point equ 34
Pattern_Loose equ 38
Pattern_Box equ 40
Pattern_End equ 41
