Char_Space equ 0

Char_Solver equ 128
Char_Solver_Left equ 128
Char_Solver_Right equ 136
Char_Solver_Up equ 144
Char_Solver_Down equ 152
Char_Monster equ 160
Char_Monster_Left equ 160
Char_Monster_Right equ 168
Char_Monster_Up equ 176
Char_Monster_Down equ 184
Char_Card equ 192
Char_End equ 248

Char_Wall equ 48
Char_Title equ 64
Char_N equ 64
Char_E equ 68
Char_U equ 72
Char_R equ 76
Char_A equ 80
Char_S equ 84
Char_End2 equ 88
