
Char_Space equ 0
Char_Logo equ 0
Char_Color equ 16
Char_Remain equ 16
Char_Terrain equ 20
Char_End equ 30

Pattern_Fighter equ 0
Pattern_SkyEnemyA equ 1
Pattern_SkyEnemyB equ 2
Pattern_SkyEnemyC equ 10
Pattern_GroundEnemyA equ 11
Pattern_GroundEnemyB equ 12
Pattern_FighterBullet equ 13
Pattern_EnemyBullet equ 14
Pattern_BarrierHead equ 15
Pattern_Bang equ 16
Pattern_SmallBang equ 16
Pattern_LargeBang equ 17
Pattern_Item equ 21
Pattern_Fort equ 22
Pattern_Score equ 23
Pattern_HighScore equ 24
Pattern_Stage equ 25
Pattern_RemainCount equ 26
Pattern_End equ 27
