
Char_Space equ 0
Char_Ascii equ 0
Char_Wall equ 64
Char_Solver equ 80

Char_Monster equ 88

Char_Card equ 96
Char_Title equ 152
Char_N equ 152

Char_E equ 160

Char_U equ 168

Char_R equ 176

Char_A equ 184

Char_S equ 192

Char_End equ 200

Pattern_Solver equ 0
Pattern_Solver_Left equ 0
Pattern_Solver_Left0 equ 0
Pattern_Solver_Left1 equ 1
Pattern_Solver_Right equ 2
Pattern_Solver_Right0 equ 2
Pattern_Solver_Right1 equ 3
Pattern_Solver_Up equ 4
Pattern_Solver_Up0 equ 4
Pattern_Solver_Up1 equ 5
Pattern_Solver_Down equ 6
Pattern_Solver_Down0 equ 6
Pattern_Solver_Down1 equ 7
Pattern_Monster equ 8
Pattern_Monster_Left equ 8
Pattern_Monster_Left0 equ 8
Pattern_Monster_Left1 equ 9
Pattern_Monster_Right equ 10
Pattern_Monster_Right0 equ 10
Pattern_Monster_Right1 equ 11
Pattern_Monster_Up equ 12
Pattern_Monster_Up0 equ 12
Pattern_Monster_Up1 equ 13
Pattern_Monster_Down equ 14
Pattern_Monster_Down0 equ 14
Pattern_Monster_Down1 equ 15
Pattern_Card equ 16
Pattern_End equ 17
