
Char_Space equ 0
Char_Logo equ 0
Char_Soil equ 16
Char_Wall equ 18
Char_Wall_Left  equ 18
Char_Wall_Right  equ 19
Char_Wall_Top  equ 20
Char_Wall_Bottom  equ 21
Char_Wall_LeftTop  equ 22
Char_Wall_RightTop  equ 23
Char_Wall_LeftBottom  equ 24
Char_Wall_RightBottom  equ 25
Char_Bedrock equ 26
Char_Color equ 27
Char_Remain equ 27
Char_Box equ 28
Char_Rock equ 32
Char_End equ 36


Pattern_Man equ 0
Pattern_Ghost equ 16
Pattern_Chaser equ 32
Pattern_Rock equ 33
Pattern_Point equ 34
Pattern_Loose equ 38
Pattern_End equ 40
