
Char_Space equ 0
Char_Ascii equ 0
Char_Logo equ 64
Char_Ground equ 80
Char_GroundFlat equ 80
Char_GroundUp equ 81
Char_GroundDown equ 82
Char_Color equ 83
Char_Remain equ 83
Char_End equ 128

Char_Fort equ 128

Pattern_MyFighter equ 0
Pattern_MyFighter_Right equ 0
Pattern_MyFighter_RightDown equ 3
Pattern_MyFighter_RightUp equ 6
Pattern_EnemyFighter equ 9
Pattern_EnemyFighter_Left equ 9
Pattern_EnemyFighter_Right equ 12
Pattern_Track equ 15
Pattern_Rocket equ 16
Pattern_SmallBang equ 17
Pattern_LargeBang equ 18
Pattern_MyBullet equ 22
Pattern_EnemyBullet equ 23
Pattern_Item equ 24
Pattern_End equ 25
