
Char_Ladder equ 0
Char_Ladder_Left equ 0
Char_Ladder_Right equ 1
Char_Floor equ 2
Char_Item equ 3
Char_Fire equ 7
Char_Monster equ 11
Char_Monster_Left equ 11
Char_Monster_Left0 equ 11
Char_Monster_Left1 equ 15
Char_Monster_Right equ 19
Char_Monster_Right0 equ 19
Char_Monster_Right1 equ 23
Char_Monster_Fall equ 27
Char_End0 equ 31


Char_Oneup equ 128
Char_Remain equ 132
Char_Man equ 136
Char_End1 equ 140

Char_Space equ 32

Ptn_Ladder equ 0
Ptn_Ladder_Left equ 0
Ptn_Ladder_Right equ 1
Ptn_Floor equ 2
Ptn_Item equ 3
Ptn_Fire equ 7
Ptn_Monster equ 11
Ptn_Monster_Left equ 11
Ptn_Monster_Left0 equ 11
Ptn_Monster_Left1 equ 15
Ptn_Monster_Right equ 19
Ptn_Monster_Right0 equ 19
Ptn_Monster_Right1 equ 23
Ptn_Monster_Fall equ 27
Ptn_Oneup equ 31
Ptn_Man equ 35
Ptn_Man_Left equ 35
Ptn_Man_Left_Stop equ 35
Ptn_Man_Left0 equ 39
Ptn_Man_Left1 equ 43
Ptn_Man_Left2 equ 47
Ptn_Man_Right equ 51
Ptn_Man_Right_Stop equ 51
Ptn_Man_Right0 equ 55
Ptn_Man_Right1 equ 59
Ptn_Man_Right2 equ 63
Ptn_Man_Climb equ 67
Ptn_Man_Climb0 equ 67
Ptn_Man_Climb1 equ 71
Ptn_End equ 75
