
Char_Space equ 0
Char_Ascii equ 0
Char_Logo equ 64
Char_Barrier equ 80
Char_Color equ 81
Char_BarrierHead equ 81
Char_Remain equ 82
Char_Fort equ 86
Char_Terrain equ 122
Char_End equ 132

Pattern_Fighter equ 0
Pattern_SkyEnemy equ 1
Pattern_SkyEnemyA equ 1
Pattern_SkyEnemyB equ 2
Pattern_SkyEnemyC equ 10
Pattern_GroundEnemy equ 11
Pattern_GroundEnemyA equ 11
Pattern_GroundEnemyB equ 12
Pattern_Bang equ 13
Pattern_SmallBang equ 13
Pattern_LargeBang equ 14
Pattern_Item equ 18
Pattern_FighterBullet equ 19
Pattern_EnemyBullet equ 20
Pattern_End equ 21
