
Char_Space equ 0
Char_Ascii equ 0
Char_Logo equ 64
Char_Star equ 80
Char_Color equ 81
Char_Enemy equ 81
Char_EnemyA equ 81
Char_EnemyB equ 85
Char_EnemyC equ 89
Char_Remain equ 93
Char_End equ 97

Pattern_Enemy equ 0
Pattern_EnemyA equ 0
Pattern_EnemyB equ 8
Pattern_EnemyC equ 16
Pattern_Fighter equ 24
Pattern_FighterBullet equ 25
Pattern_EnemyBullet equ 26
Pattern_Bang equ 27
Pattern_Item equ 32
Pattern_End equ 33
