
Char_Wall equ 0
Char_Monster equ 16
Char_End0 equ 32


Char_FireBullet equ 128
Char_Fire equ 132
Char_Dot equ 136
Char_Food equ 140
Char_Man equ 144
Char_Remain equ 148
Char_End1 equ 152

Char_Space equ 32


Pattern_Wall equ 0
Pattern_Man equ 16
Pattern_Man_Left equ 16
Pattern_Man_Left0 equ 16
Pattern_Man_Left1 equ 20
Pattern_Man_Right equ 24
Pattern_Man_Right0 equ 24
Pattern_Man_Right1 equ 28
Pattern_Man_Up equ 32
Pattern_Man_Up0 equ 32
Pattern_Man_Up1 equ 36
Pattern_Man_Down equ 40
Pattern_Man_Down0 equ 40
Pattern_Man_Down1 equ 44
Pattern_Monster equ 48
Pattern_Monster_Left equ 48
Pattern_Monster_Left0 equ 48
Pattern_Monster_Left1 equ 52
Pattern_Monster_Right equ 56
Pattern_Monster_Right0 equ 56
Pattern_Monster_Right1 equ 60
Pattern_Monster_Up equ 64
Pattern_Monster_Up0 equ 64
Pattern_Monster_Up1 equ 68
Pattern_Monster_Down equ 72
Pattern_Monster_Down0 equ 72
Pattern_Monster_Down1 equ 76
Pattern_FireBullet equ 80
Pattern_Fire equ 84
Pattern_Dot equ 88
Pattern_Food equ 92
Pattern_End equ 96
