
Char_Space equ 0
Char_Ascii equ 0
Char_Logo equ 30
Char_Remain equ 45
Char_Color equ 46
Char_Terrain equ 46
Char_Terrain0 equ 46
Char_Terrain1 equ 77
Char_End equ 108

Char_Fort equ 172
Char_Fort0 equ 172
Char_Fort1 equ 214
Char_FortEnd equ 256

Pattern_FighterBullet equ 0
Pattern_EnemyBullet equ 1
Pattern_Barrier equ 2
Pattern_BarrierLeft equ 2
Pattern_BarrierCenter equ 3
Pattern_BarrierRight equ 4
Pattern_Bang equ 5
Pattern_SmallBang equ 5
Pattern_LargeBang equ 6
Pattern_Item equ 10
Pattern_Fighter equ 11
Pattern_SkyEnemy equ 13
Pattern_SkyEnemyA equ 13
Pattern_SkyEnemyB equ 15
Pattern_SkyEnemyC equ 31
Pattern_GroundEnemy equ 33
Pattern_GroundEnemyA equ 33
Pattern_GroundEnemyB equ 35
Pattern_End equ 37
