
Char_Space equ 0
Char_Ascii equ 0
Char_Logo equ 64
Char_Wall equ 80
Char_Wall_Left equ 80
Char_Wall_Right equ 81
Char_Wall_Top equ 82
Char_Wall_Bottom equ 83
Char_Wall_LeftTop equ 84
Char_Wall_RightTop equ 85
Char_Wall_LeftBottom equ 86
Char_Wall_RightBottom equ 87
Char_Color equ 88
Char_Soil equ 88
Char_Bedrock equ 92
Char_Rock equ 96
Char_Box equ 100
Char_Remain equ 104
Char_End equ 108

Pattern_Man equ 0
Pattern_Ghost equ 16
Pattern_Chaser equ 32
Pattern_Rock equ 33
Pattern_Point equ 34
Pattern_Loose equ 38
Pattern_End equ 40
